# Generated by Django 2.0.5 on 2018-06-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_song_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeralEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Song')),
            ],
        ),
    ]
