# Generated by Django 2.0.5 on 2018-05-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'defaults'),
        ('core', '0003_auto_20180528_0214'),
    ]

    operations = [
    ]
