# Generated by Django 2.0.5 on 2018-05-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20180528_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='track_ids',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='album_ids',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='track_ids',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='track_ids',
            field=models.BinaryField(),
        ),
    ]
