# Generated by Django 2.0.5 on 2018-05-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180528_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='track_ids',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='album_ids',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='track_ids',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='track_ids',
        ),
    ]
