# Generated by Django 2.0.5 on 2018-05-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180529_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art',
            field=models.CharField(blank=True, default='', max_length=50000),
        ),
    ]
