# Generated by Django 2.0.5 on 2018-05-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180529_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='TALB',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TCON',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TCOP',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='song',
            name='TDRC',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TIT2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TOPE',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TPE1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TPE2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='TRCK',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='WXXX',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
