# Generated by Django 2.0.5 on 2018-05-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180529_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='num_tracks',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='num_albums',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='num_tracks',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='num_tracks',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='core.Artist'),
        ),
    ]
