# Generated by Django 2.0.5 on 2018-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_song_bitrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='sample_rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
