# Generated by Django 2.0.5 on 2018-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_song_sample_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
