# Generated by Django 2.0.5 on 2018-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_song_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='num_tracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='num_albums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='num_tracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='num_tracks',
            field=models.IntegerField(default=0),
        ),
    ]
