# Generated by Django 2.0.5 on 2018-06-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_song_audio_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mime_type',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
